version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
  versioning-strategy: auto
  open-pull-requests-limit: 10
  groups:
    dev-dependencies:
      patterns:
        - "@types/*"
        - "eslint*"
        - "@typescript-eslint/*"
        - "prettier"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: weekly
  open-pull-requests-limit: 10
