name: Test
on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: npm run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Update npm
        run: npm install -g npm@11

      - name: Install dependencies
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: npm run test
        run: npm run test
