name: Test
on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: npm run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Update npm
        run: npm install -g npm@8

      - name: Install dependencies
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: npm run test
        run: npm run test
